RSI_BUY_THRESHOLD = 30
RSI_SELL_THRESHOLD = 70
RETRY_DELAY = 5
ASSET = 'USDT'
MONGO_CONNECTION_STRING = os.getenv('MONGO_CONNECTION_STRING', 'mongodb://localhost:27017/')
SYMBOL = os.getenv('SYMBOL', 'BTCUSDT')
